/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AgriSensorDataInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "DEVICE_ROLE"
      | "FARMER_ROLE"
      | "RESEARCHER_ROLE"
      | "SUPPLY_CHAIN_ROLE"
      | "cropEvents"
      | "dataHashes"
      | "farmToCropEvents"
      | "farmToReadings"
      | "getCropEventsByFarm"
      | "getReadingsByFarm"
      | "getRoleAdmin"
      | "getSupplyChainStages"
      | "getTotalCropEvents"
      | "getTotalReadings"
      | "getTotalSupplyChainStages"
      | "grantRole"
      | "hasRole"
      | "productToStages"
      | "readings"
      | "recordCropEvent"
      | "recordSupplyChainStage"
      | "renounceRole"
      | "revokeRole"
      | "submitBatch"
      | "submitSensorData"
      | "supplyChainStages"
      | "supportsInterface"
      | "verifyReading"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AnomalyDetected"
      | "CropEventRecorded"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "SensorDataSubmitted"
      | "SupplyChainStageRecorded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEVICE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FARMER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RESEARCHER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SUPPLY_CHAIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cropEvents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dataHashes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "farmToCropEvents",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "farmToReadings",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCropEventsByFarm",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReadingsByFarm",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSupplyChainStages",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalCropEvents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalReadings",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalSupplyChainStages",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "productToStages",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "readings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordCropEvent",
    values: [BigNumberish, string, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordSupplyChainStage",
    values: [BigNumberish, string, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitBatch",
    values: [BigNumberish[], BigNumberish[], BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "submitSensorData",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supplyChainStages",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyReading",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEVICE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FARMER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RESEARCHER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SUPPLY_CHAIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cropEvents", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dataHashes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "farmToCropEvents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "farmToReadings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCropEventsByFarm",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReadingsByFarm",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSupplyChainStages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalCropEvents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalReadings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalSupplyChainStages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "productToStages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "readings", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordCropEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordSupplyChainStage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitSensorData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supplyChainStages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyReading",
    data: BytesLike
  ): Result;
}

export namespace AnomalyDetectedEvent {
  export type InputTuple = [
    readingId: BigNumberish,
    deviceId: AddressLike,
    anomalyType: string
  ];
  export type OutputTuple = [
    readingId: bigint,
    deviceId: string,
    anomalyType: string
  ];
  export interface OutputObject {
    readingId: bigint;
    deviceId: string;
    anomalyType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CropEventRecordedEvent {
  export type InputTuple = [
    eventId: BigNumberish,
    farmId: BigNumberish,
    eventType: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    eventId: bigint,
    farmId: bigint,
    eventType: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    eventId: bigint;
    farmId: bigint;
    eventType: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SensorDataSubmittedEvent {
  export type InputTuple = [
    readingId: BigNumberish,
    deviceId: AddressLike,
    farmId: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    readingId: bigint,
    deviceId: string,
    farmId: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    readingId: bigint;
    deviceId: string;
    farmId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SupplyChainStageRecordedEvent {
  export type InputTuple = [
    stageId: BigNumberish,
    productId: BigNumberish,
    stage: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    stageId: bigint,
    productId: bigint,
    stage: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    stageId: bigint;
    productId: bigint;
    stage: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgriSensorData extends BaseContract {
  connect(runner?: ContractRunner | null): AgriSensorData;
  waitForDeployment(): Promise<this>;

  interface: AgriSensorDataInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DEVICE_ROLE: TypedContractMethod<[], [string], "view">;

  FARMER_ROLE: TypedContractMethod<[], [string], "view">;

  RESEARCHER_ROLE: TypedContractMethod<[], [string], "view">;

  SUPPLY_CHAIN_ROLE: TypedContractMethod<[], [string], "view">;

  cropEvents: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, string, string] & {
        farmId: bigint;
        eventType: string;
        timestamp: bigint;
        notes: string;
        linkedDataHash: string;
      }
    ],
    "view"
  >;

  dataHashes: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  farmToCropEvents: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  farmToReadings: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getCropEventsByFarm: TypedContractMethod<
    [farmId: BigNumberish],
    [bigint[]],
    "view"
  >;

  getReadingsByFarm: TypedContractMethod<
    [farmId: BigNumberish],
    [bigint[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getSupplyChainStages: TypedContractMethod<
    [productId: BigNumberish],
    [bigint[]],
    "view"
  >;

  getTotalCropEvents: TypedContractMethod<[], [bigint], "view">;

  getTotalReadings: TypedContractMethod<[], [bigint], "view">;

  getTotalSupplyChainStages: TypedContractMethod<[], [bigint], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  productToStages: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  readings: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, bigint, string] & {
        timestamp: bigint;
        deviceId: string;
        farmId: bigint;
        temperature: bigint;
        soilMoisture: bigint;
        humidity: bigint;
        dataHash: string;
      }
    ],
    "view"
  >;

  recordCropEvent: TypedContractMethod<
    [
      farmId: BigNumberish,
      eventType: string,
      notes: string,
      linkedDataHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  recordSupplyChainStage: TypedContractMethod<
    [
      productId: BigNumberish,
      stage: string,
      location: string,
      linkedDataHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  submitBatch: TypedContractMethod<
    [
      farmIds: BigNumberish[],
      temperatures: BigNumberish[],
      moistures: BigNumberish[],
      humidities: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  submitSensorData: TypedContractMethod<
    [
      farmId: BigNumberish,
      temperature: BigNumberish,
      soilMoisture: BigNumberish,
      humidity: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  supplyChainStages: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, string, string, string] & {
        productId: bigint;
        stage: string;
        timestamp: bigint;
        recorder: string;
        location: string;
        linkedDataHash: string;
      }
    ],
    "view"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  verifyReading: TypedContractMethod<
    [readingId: BigNumberish],
    [[boolean, string] & { valid: boolean; storedHash: string }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEVICE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "FARMER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RESEARCHER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SUPPLY_CHAIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cropEvents"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, string, string] & {
        farmId: bigint;
        eventType: string;
        timestamp: bigint;
        notes: string;
        linkedDataHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "dataHashes"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "farmToCropEvents"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "farmToReadings"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCropEventsByFarm"
  ): TypedContractMethod<[farmId: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getReadingsByFarm"
  ): TypedContractMethod<[farmId: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getSupplyChainStages"
  ): TypedContractMethod<[productId: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getTotalCropEvents"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalReadings"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalSupplyChainStages"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "productToStages"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "readings"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, bigint, string] & {
        timestamp: bigint;
        deviceId: string;
        farmId: bigint;
        temperature: bigint;
        soilMoisture: bigint;
        humidity: bigint;
        dataHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordCropEvent"
  ): TypedContractMethod<
    [
      farmId: BigNumberish,
      eventType: string,
      notes: string,
      linkedDataHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordSupplyChainStage"
  ): TypedContractMethod<
    [
      productId: BigNumberish,
      stage: string,
      location: string,
      linkedDataHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitBatch"
  ): TypedContractMethod<
    [
      farmIds: BigNumberish[],
      temperatures: BigNumberish[],
      moistures: BigNumberish[],
      humidities: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitSensorData"
  ): TypedContractMethod<
    [
      farmId: BigNumberish,
      temperature: BigNumberish,
      soilMoisture: BigNumberish,
      humidity: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supplyChainStages"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, string, string, string] & {
        productId: bigint;
        stage: string;
        timestamp: bigint;
        recorder: string;
        location: string;
        linkedDataHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyReading"
  ): TypedContractMethod<
    [readingId: BigNumberish],
    [[boolean, string] & { valid: boolean; storedHash: string }],
    "view"
  >;

  getEvent(
    key: "AnomalyDetected"
  ): TypedContractEvent<
    AnomalyDetectedEvent.InputTuple,
    AnomalyDetectedEvent.OutputTuple,
    AnomalyDetectedEvent.OutputObject
  >;
  getEvent(
    key: "CropEventRecorded"
  ): TypedContractEvent<
    CropEventRecordedEvent.InputTuple,
    CropEventRecordedEvent.OutputTuple,
    CropEventRecordedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SensorDataSubmitted"
  ): TypedContractEvent<
    SensorDataSubmittedEvent.InputTuple,
    SensorDataSubmittedEvent.OutputTuple,
    SensorDataSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "SupplyChainStageRecorded"
  ): TypedContractEvent<
    SupplyChainStageRecordedEvent.InputTuple,
    SupplyChainStageRecordedEvent.OutputTuple,
    SupplyChainStageRecordedEvent.OutputObject
  >;

  filters: {
    "AnomalyDetected(uint256,address,string)": TypedContractEvent<
      AnomalyDetectedEvent.InputTuple,
      AnomalyDetectedEvent.OutputTuple,
      AnomalyDetectedEvent.OutputObject
    >;
    AnomalyDetected: TypedContractEvent<
      AnomalyDetectedEvent.InputTuple,
      AnomalyDetectedEvent.OutputTuple,
      AnomalyDetectedEvent.OutputObject
    >;

    "CropEventRecorded(uint256,uint256,string,uint256)": TypedContractEvent<
      CropEventRecordedEvent.InputTuple,
      CropEventRecordedEvent.OutputTuple,
      CropEventRecordedEvent.OutputObject
    >;
    CropEventRecorded: TypedContractEvent<
      CropEventRecordedEvent.InputTuple,
      CropEventRecordedEvent.OutputTuple,
      CropEventRecordedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SensorDataSubmitted(uint256,address,uint256,uint256)": TypedContractEvent<
      SensorDataSubmittedEvent.InputTuple,
      SensorDataSubmittedEvent.OutputTuple,
      SensorDataSubmittedEvent.OutputObject
    >;
    SensorDataSubmitted: TypedContractEvent<
      SensorDataSubmittedEvent.InputTuple,
      SensorDataSubmittedEvent.OutputTuple,
      SensorDataSubmittedEvent.OutputObject
    >;

    "SupplyChainStageRecorded(uint256,uint256,string,uint256)": TypedContractEvent<
      SupplyChainStageRecordedEvent.InputTuple,
      SupplyChainStageRecordedEvent.OutputTuple,
      SupplyChainStageRecordedEvent.OutputObject
    >;
    SupplyChainStageRecorded: TypedContractEvent<
      SupplyChainStageRecordedEvent.InputTuple,
      SupplyChainStageRecordedEvent.OutputTuple,
      SupplyChainStageRecordedEvent.OutputObject
    >;
  };
}
